### ISSUE TITLE
Received an exception after creating an account and while logging in.

### ISSUE THREAD

**Issue by IamSanjid** [HoLLy-HaCKeR/PokeOneToolkit#3]
Check the picture sorry forgot to copy the exception.
http://prntscr.com/l5ym4g

Edit:
Found the exception this is received whenever you try to login with a fully new account.
Exception:
`System.NullReferenceException: Object reference not set to an instance of an object
  at PokeOneToolkit.Runtime.HandlerPsx.HandleRecv (PSXAPI.Proto& proto) [0x000f2] in <b214c5bb8c0c4301bd4cb0ad3c4db582>:0`

And so far it happend for the `login.Skin` or `login.Equip` was null.
So it needs a simple fix.

**Comment by holly-hacker** [comment]
Yeah, looks like it just needs a null check.
